### ISSUE TITLE
Rework public API

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-reports#40]
Beans `Reports` (ReportingApi and ReportService in CUBA) should be split into several smaller beans. Multiple overloaded methods for running reports must be replaced with a fluent builder.

Current implementation:
### Core part:

1. `ReportRunContext `- class to store the information required for report running (report, report template, input parameters, output name pattern, output file type):
     **Creation examples:**
 ```java
 ReportRunContext context = new ReportRunContext(report)
                  .addParam("customer", customer)
                  .addParam("minOrdersDate", date)
                  .setOutputNamePattern("Orders");
 
  ReportRunContext context = new ReportRunContext(report)
                  .setReportTemplate(template)
                  .setOutputType(ReportOutputType.PDF)
                  .setParams(paramsMap);
```

2. `FluentReportRunner` - API to create `RunReportContext` or run a report with parameters that are specified for the runner. 
3. `ReportRunner` - API to run reports that have methods to run a report by using `ReportRunContext ` object and create the `FluentReportRunner` by report entity or code. All methods return the `ReportOutputDocument`  object that contains the result of report execution.
**Usage examples:**
```java
ReportOutputDocument document = reportRunner.run(new ReportRunContext(report).setParams(paramsMap));

ReportOutputDocument document = reportRunner.byReportCode("orders-report")
                      .addParam("orders", ordersList)
                      .withTemplateCode("orders-template")
                      .run();

ReportOutputDocument document = reportRunner.byReportEntity(report)
                      .addParam("orders", orders)
                      .withOutputType(ReportOutputType.PDF)
                      .withOutputNamePattern("Orders")
                      .run();
```
4. `ReportZipUtils` - helps to package a list of `ReportOutputDocument` objects into one ZIP archive.
**Usage example:**
```java
byte[] zipBytes = reportZipUtils.createZipArchive(reportOutputDocuments);
```

### UI part:
1. `UiReportRunContext`- class to store the information required to run a report from UI (report, report template, input parameters, output file name, output file type, need to show InputParameterDialog before run, run in the background or synchronously) and show the result. **Note:** If a report runs in the background, the screen (or screen fragment) from which the report runs should be specified as well.
     **Creation examples:**
 ```java
  UiReportRunContext context = new UiReportRunContext(report)
                  .addParam("customers", customersList)
                  .setOutputNamePattern("Customers")
                  .setOriginFrameOwner(screen)
                  .setInBackground(true)
                  .setParametersDialogShowMode(ParametersDialogShowMode.NO);
 
   UiReportRunContext context = new UiReportRunContext(report)
                  .setReportTemplate(template)
                  .setOutputType(ReportOutputType.PDF)
                  .setParams(paramsMap);
```

2. `FluentUiReportRunner` - API to create `UiRunReportContext` or run a report with parameters that specified for the runner. 
3. `UiReportRunner` - API to run reports from UI that have methods:
    - Run a report by using the `UiReportRunContext ` object
    - Create the `FluentUiReportRunner` by report entity or code
    - Run a report several times for the specified parameter alias and values

As result of methods execution the `ReportOutpuDocument` is downloaded or the result is shown (in case of chart/pivot table/table templates).

**Usage examples:**
```java
uiReportRunner.runAndShow(new UiReportRunContext(report).setParams(paramsMap));

uiReportRunner.byReportCode("orders-report")
                      .addParam("orders", ordersList)
                      .withParametersDialogShowMode(ParametersDialogShowMode.NO)
                      .runAndShow();

uiReportRunner.byReportEntity(report)
                      .withTemplateCode("order-template")
                      .withOutputNamePattern("Orders")
                      .withParametersDialogShowMode(ParametersDialogShowMode.IF_REQUIRED)
                      .inBackground(screen)
		      .runAndShow();

uiReportRunner.byReportEntity(report)
                      .addParam("minOrdersDate", date)
                      .withOutputType(ReportOutputType.PDF)
                      .withTemplateCode(""orders-template"")
                      .runMultipleReports("customer", customersList);
```
### Task List

- [x] Core report runner
- [x] UI report runner
- [x] Get rid of old API usage

### Progress

2021-06-22 100%

### To QA:
1. Reports add-on: Check report run (with the 'jmix.reports.client.useBackgroundReportProcessing' property on/off):
		a) listPrintForm action;
		b) editorPrintForm action (with outputNamePattern and not);
		c) runReport action (with one report, with several reports, reports with/without parameters)
		d) run report from reports REST (with/without template code)
		e) From Reports browser (reports with/without parameters, one/several templates, template with alterable output)
		f) Show charts/pivot tables/tables screens (report runs synchronously only)
		g) From Region/Query step in wizard
		h) From Report editor
2. Reports add-on: Check filling the execution history after report run if it is enabled
2. Email templates add-on: Check the result in email sent from from EmailSendScreen
3. Dashboards add-on: ChartWidget (with/without widget parameters): chart is shown correctly

**Comment by BryanYin** [comment]
Hi, these APIs are not documented in CUBA, should we add them in Jmix?

**Comment by gorbunkov** [comment]
@BryanYin This API is not finished yet at probably will be changed a bit in the nearest future.

**Comment by BryanYin** [comment]
@gorbunkov ok, thanks. So, this part should be added into document after development done, right?

**Comment by gorbunkov** [comment]
@BryanYin 

> So, this part should be added into document after development done, right?

Yes

**Comment by owlet1997** [comment]
- [ ] Reports add-on: Check report run (with the 'jmix.reports.client.useBackgroundReportProcessing' property on):
- [ ] a) listPrintForm action;
- [ ] b) editorPrintForm action (with outputNamePattern and not);
- [ ] c) runReport action (with one report, with several reports, reports with/without parameters)
- [ ] d) run report from reports REST (with/without template code)
- [ ] e) From Reports browser (reports with/without parameters, one/several templates, template with alterable output)
- [ ] f) Show charts/pivot tables/tables screens (report runs synchronously only)
- [ ] g) From Region/Query step in wizard
- [ ] h) From Report editor

- [ ] Reports add-on: Check report run (with the 'jmix.reports.client.useBackgroundReportProcessing' property off):
- [ ] a) listPrintForm action;
- [ ] b) editorPrintForm action (with outputNamePattern and not);
- [ ] c) runReport action (with one report, with several reports, reports with/without parameters)
- [ ] d) run report from reports REST (with/without template code)
- [ ] e) From Reports browser (reports with/without parameters, one/several templates, template with alterable output)
- [ ] f) Show charts/pivot tables/tables screens (report runs synchronously only)
- [ ] g) From Region/Query step in wizard
- [ ] h) From Report editor

- [ ] Reports add-on: Check filling the execution history after report run if it is enabled
- [ ] Email templates add-on: Check the result in email sent from from EmailSendScreen
- [ ] Dashboards add-on: ChartWidget (with/without widget parameters): chart is shown correctly

**Comment by owlet1997** [comment]
- [ ] Reports add-on: Check report run (with the 'jmix.reports.client.useBackgroundReportProcessing' property off):
- [ ] a) listPrintForm action;
- [ ] b) editorPrintForm action;
- [ ] b.1 with outputNamePattern
- [ ] b.2 without outputNamePattern
- [ ] c) runReport action
- [ ] c.1. with one report,
- [ ] c.2  with several reports, 
- [ ] c.3 reports with parameters,
- [ ] c.4 reports without parameters,
- [ ] d) run report from reports REST (with/without template code)
- [ ] d.1 withtemplate code
- [ ] d.2 without template code
- [ ] e) From Reports browser  
- [ ] e.1 reports with parameters
- [ ] e.2 reports without parameters
- [ ] e.3 reports one templates,
- [ ] e.4 reports several templates,
- [ ] e.5 template with alterable output)
- [ ] f) Show charts/pivot tables/tables screens (report runs synchronously only)
- [ ] f.1 charts
- [ ] f.2 pivot tables
- [ ] f.3 tables 
- [ ] g) From Region/Query step in wizard
- [ ] g.1  From Region step in wizard
- [ ] g.2 From Query step in wizard
- [ ] h) From Report editor

**Comment by owlet1997** [comment]
- [ ] Reports add-on: Check filling the execution history after report run if it is enabled
- [ ] Email templates add-on: Check the result in email sent from from EmailSendScreen
- [ ] Dashboards add-on: ChartWidget (with/without widget parameters): chart is shown correctly
